#ifndef _BCL_STATUS_H
#define _BCL_STATUS_H

typedef enum 
{
    BCL_OK                      = 0,
    BCL_INVALID_PARAMETER,
    BCL_BUFFER_TOO_SMALL,
    BCL_OUT_OF_RESOURCES,
    BCL_NOT_FOUND,
    BCL_ALREADY_EXISTS,
    BCL_BAD_PACKET_START,
    BCL_BAD_PACKET_END,
    BCL_OPCODE_MISMATCH,
    BCL_ROBOT_ID_MISMATCH,
    BCL_PAYLOAD_SIZE_MISMATCH,
    BCL_CLIPPED_PACKET,
    BCL_CHECKSUM_ERROR,
    BCL_UNSUPPORTED,
    BCL_SOCKET_ERROR,
    BCL_SERIAL_ERROR,
    BCL_GENERIC_ERROR = 255
} BCL_STATUS;

#endif